reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
script:
  - gem install cocoapods
  - cd Example; pod install; cd ../;
  - xctool test -workspace Example/AMEEnumeratedObject.xcworkspace -scheme AMEEnumeratedObject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
